/* SR Contenidos 2.0 — frontend 100% web */
const { createClient } = window.supabase;
const cfg = window.SR_CONFIG || {};
const sb = createClient(cfg.url, cfg.publishableKey, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } });

let db = null;
const state = { view: 'dashboard', clientId: null, contentFilter: 'Todos', theme: localStorage.getItem('sr20_theme') || 'day' };
const CATEGORIES = [
  { name: 'Construcción y hogar', rubrics: ['Ferretería','Corralón','Sanitarios','Pinturería','Materiales eléctricos','Metalúrgica'] },
  { name: 'Automotor', rubrics: ['Taller mecánico','Concesionaria','Lubricentro','Gomería'] }
];
const REEL_STATUSES = ['Idea','Para grabar','Grabado','Editando','Listo','Enviado al cliente','Publicado'];
const APPROVALS = ['Pendiente','Aprobado','Cambios solicitados'];
const EVENT_TYPES = ['Grabación','Contenido extra','Edición','Reunión','Publicación','Otro'];

function esc(v){return String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function client(id){return db?.clients?.find(c=>String(c.id)===String(id));}
function planByReels(n){return db?.plans?.find(p=>Number(p.reels)===Number(n));}
function allReels(){return db?.reels || [];}
function money(v){return '$'+Number(v||0).toLocaleString('es-AR');}
function fmtDate(v){return v?new Date(v).toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'}):'—';}
function toast(message, kind='ok'){
  const root=document.getElementById('toast-root'); if(!root)return alert(message);
  const el=document.createElement('div'); el.className='notice '+(kind==='error'?'danger-notice':'success'); el.textContent=message; el.style.cssText='position:fixed;right:18px;bottom:18px;z-index:5000;max-width:420px;box-shadow:0 8px 30px rgba(0,0,0,.18)'; root.appendChild(el); setTimeout(()=>el.remove(),3200);
}
function fail(e){console.error(e); toast(e?.message || String(e) || 'Ocurrió un error.', 'error');}
async function ensureOk(promise){
  if(promise instanceof Response){
    const res=promise;
    const data=await res.json().catch(()=>({}));
    if(!res.ok) throw new Error(data?.error || data?.message || `Error HTTP ${res.status}`);
    return data;
  }
  const {data,error}=await promise;if(error)throw error;return data;
}
function applyTheme(){document.documentElement.dataset.theme=state.theme;}
function stat(label,value){return `<div class="card stat"><div class="label">${esc(label)}</div><div class="value">${value}</div></div>`;}
function kpi(label,value){return `<div><div class="pill">${esc(label)}</div><div class="kpi">${Number(value||0).toLocaleString('es-AR')}</div></div>`;}

async function getCurrentUser(){
  const {data:{user}}=await sb.auth.getUser();
  return user || null;
}
async function loadDb(){
  const user=await getCurrentUser();
  if(!user){db=null;return;}
  const {data:{session}}=await sb.auth.getSession();
  const sessionProfile=await fetch('/api/session-profile',{headers:{Authorization:`Bearer ${session?.access_token||''}`},cache:'no-store'});
  const profile=await ensureOk(sessionProfile);
  const isAdmin=profile.role==='admin';
  const clientsQ=isAdmin?sb.from('sr20_clients').select('*').order('created_at',{ascending:true}):sb.from('sr20_clients').select('*').eq('id',profile.client_id);
  const [clients,plans,reels,payments,events,messages]=await Promise.all([
    ensureOk(clientsQ),
    ensureOk(sb.from('sr20_plans').select('*').eq('active',true).order('sort_order',{ascending:true}).order('created_at',{ascending:true})),
    ensureOk(isAdmin?sb.from('sr20_reels').select('*').order('created_at',{ascending:true}):sb.from('sr20_reels').select('*').eq('client_id',profile.client_id).order('created_at',{ascending:true})),
    ensureOk(isAdmin?sb.from('sr20_payments').select('*').order('paid_at',{ascending:false}):sb.from('sr20_payments').select('*').eq('client_id',profile.client_id).order('paid_at',{ascending:false})),
    ensureOk(isAdmin?sb.from('sr20_calendar_events').select('*').order('start_at',{ascending:true}):sb.from('sr20_calendar_events').select('*').eq('client_id',profile.client_id).order('start_at',{ascending:true})),
    ensureOk(isAdmin?sb.from('sr20_messages').select('*').order('created_at',{ascending:true}):sb.from('sr20_messages').select('*').eq('client_id',profile.client_id).order('created_at',{ascending:true}))
  ]);
  const ids=reels.map(r=>r.id);
  let stats=[];
  if(ids.length) stats=await ensureOk(sb.from('sr20_stats').select('*').in('reel_id',ids).order('created_at',{ascending:true}));
  const mappedReels=reels.map(r=>({id:r.id,clientId:r.client_id,title:r.title,format:r.format,status:r.status,published:r.published||'',approvalStatus:r.approval_status||'Pendiente',stats:stats.filter(s=>s.reel_id===r.id).map(s=>({id:s.id,label:s.label,hours:Number(s.hours||0),views:Number(s.views||0),likes:Number(s.likes||0),saves:Number(s.saves||0),shares:Number(s.shares||0),reposts:Number(s.reposts||0),sourceImageName:s.source_image_name||''}))}));
  const mappedClients=clients.map(c=>({id:c.id,name:c.name,contact:c.contact||'',phone:c.phone||'',instagram:c.instagram||'',category:c.category||'',rubric:c.rubric||'',plan:Number(c.plan||4),status:c.status,notes:c.notes||'',planPrice:Number(c.plan_price||0),color:c.color||'#0ea5e9'}));
  const mappedPayments=payments.map(p=>({id:p.id,clientId:p.client_id,amount:Number(p.amount),paidAt:p.paid_at,method:p.method||'',note:p.note||''}));
  const mappedEvents=events.map(e=>({id:e.id,clientId:e.client_id,title:e.title,type:e.type,startAt:e.start_at,endAt:e.end_at||'',price:Number(e.price||0),paymentStatus:e.payment_status,note:e.note||''}));
  const mappedMessages=messages.map(m=>({id:m.id,clientId:m.client_id,senderUserId:m.sender_user_id,body:m.body,readAt:m.read_at,createdAt:m.created_at,senderRole:m.sender_user_id===user.id?profile.role:(profile.role==='admin'?'client':'admin'),senderName:m.sender_user_id===user.id?profile.name:(profile.role==='admin'?(client(m.client_id)?.name||'Cliente'):'SR Contenidos')}));
  const now=Date.now();
  const alerts=mappedReels.filter(r=>r.published&&r.status!=='Publicado'&&r.approvalStatus!=='Aprobado').map(r=>{const hours=(new Date(r.published).getTime()-now)/3600000;return {r,hours};}).filter(x=>x.hours>0&&x.hours<=72).map(x=>({level:x.hours<=24?'urgent':'warning',reelId:x.r.id,clientId:x.r.clientId,title:x.r.title,published:x.r.published,hoursLeft:Math.round(x.hours)}));
  db={user:{id:user.id,name:profile.name||user.email,email:profile.email||user.email,role:profile.role,clientId:profile.client_id||null},clients:mappedClients,categories:CATEGORIES,plans:plans.map(p=>({...p,reels:Number(p.reels),gift_reels:Number(p.gift_reels),price:Number(p.price),active:Boolean(p.active)})),reels:mappedReels,payments:mappedPayments,events:mappedEvents,messages:mappedMessages,alerts,reminders:[]};
}

function nav(v,label,icon){return `<button class="${state.view===v?'active':''}" data-view="${v}">${icon} &nbsp; ${label}</button>`;}
function title(){return ({dashboard:db.user.role==='admin'?'Dashboard':'Mi panel',clients:'Clientes',content:db.user.role==='admin'?'Contenidos':'Mis contenidos',calendar:'Calendario',finances:'Cobros',messages:'Mensajes',stats:db.user.role==='admin'?'Estadísticas':'Mis estadísticas',portfolio:'Portafolio',settings:'Configuración'})[state.view]||'SR Contenidos 2.0';}
function shell(inner){
 return `<div class="shell"><aside class="sidebar"><div class="brand">SR <span>Contenidos 2.0</span></div><div class="nav">${db.user.role==='admin'?nav('dashboard','Dashboard','🏠'):nav('dashboard','Mi panel','🏠')}${db.user.role==='admin'?nav('clients','Clientes','👥'):''}${nav('content',db.user.role==='admin'?'Contenidos':'Mis contenidos','🎬')}${nav('calendar','Calendario','📅')}${nav('finances','Cobros','💰')}${nav('messages','Mensajes','💬')}${nav('stats',db.user.role==='admin'?'Estadísticas':'Mis estadísticas','📊')}${nav('portfolio','Portafolio','🖼️')}${db.user.role==='admin'?nav('settings','Configuración','⚙️'):''}</div><div class="sidebar-bottom"><small class="muted">Sesión</small><b>${esc(db.user.name)}</b><button class="btn secondary small" data-logout>Salir</button></div></aside><main class="main"><div class="topbar"><div><div class="muted">SR Contenidos 2.0</div><h1>${esc(title())}</h1></div><div class="pill">☁️ Datos online</div></div><section class="content-area">${inner}</section></main></div>${modalHtml()}`;
}
function dashboard(){
 if(db.user.role==='client'){
   const c=db.clients[0], rs=allReels(), pub=rs.filter(r=>r.status==='Publicado').length, pending=rs.filter(r=>(r.approvalStatus||'Pendiente')==='Pendiente').length;
   return `<div class="grid stats">${stat('Reels del plan',c?.plan||0)}${stat('Publicados',pub)}${stat('Pendientes de aprobación',pending)}${stat('Progreso',Math.round(pub/Math.max(1,c?.plan||1)*100)+'%')}</div><div class="grid two" style="margin-top:16px"><div class="card"><h3>Bienvenido</h3><p class="muted">${esc(c?.name||db.user.name)}</p><p>Revisá tus contenidos, aprobá los que estén listos o solicitá cambios.</p></div><div class="card"><h3>Últimos contenidos</h3>${rs.slice(-6).reverse().map(r=>`<div class="row" style="padding:10px 0;border-bottom:1px solid #eef2f7"><span><b>${esc(r.title)}</b><br><small class="muted">${esc(r.status)}</small></span><span class="badge">${esc(r.approvalStatus)}</span></div>`).join('')||'<div class="empty">No hay contenidos.</div>'}</div></div>`;
 }
 const published=allReels().filter(r=>r.status==='Publicado').length, pending=allReels().filter(r=>r.status!=='Publicado').length, payments=db.payments||[];
 const totalPending=Math.max(0,db.clients.reduce((sum,c)=>sum+Number(c.planPrice||0),0)-payments.reduce((sum,p)=>sum+Number(p.amount||0),0));
 return `<div class="grid stats">${stat('Clientes activos',db.clients.filter(c=>c.status==='Activo').length)}${stat('Reels publicados',published)}${stat('Reels pendientes',pending)}${stat('Por cobrar',money(totalPending))}</div><div class="card" style="margin-top:16px"><div class="row"><div><h3>🔔 Alertas de producción</h3><div class="muted">Control de publicaciones dentro de las próximas 72 h sin aprobación.</div></div><span class="badge">${db.alerts.length}</span></div>${db.alerts.length?db.alerts.map(a=>`<div class="alert ${a.level}" style="margin-top:10px"><b>${a.level==='urgent'?'🔴 URGENTE':'🟡 ATENCIÓN'}</b> · ${esc(client(a.clientId)?.name||'Cliente')} — ${esc(a.title)}<br><span>Publicación: ${fmtDate(a.published)} · Faltan aprox. ${a.hoursLeft} h.</span></div>`).join(''):'<div class="empty" style="margin-top:10px">Todo en orden.</div>'}</div><div class="grid two" style="margin-top:16px"><div class="card"><h3>💰 Cobros pendientes</h3>${db.clients.map(c=>{const paid=payments.filter(p=>p.clientId===c.id).reduce((a,p)=>a+Number(p.amount),0),due=Math.max(0,Number(c.planPrice||0)-paid);return due?`<div class="row" style="padding:10px 0;border-bottom:1px solid #eef2f7"><span><b>${esc(c.name)}</b><br><small class="muted">Pagado: ${money(paid)}</small></span><b>${money(due)}</b></div>`:''}).join('')||'<div class="empty">No hay saldos pendientes.</div>'}</div><div class="card"><h3>📅 Próximas actividades</h3>${(db.events||[]).filter(e=>new Date(e.startAt)>=new Date()).slice(0,6).map(e=>`<div class="row" style="padding:10px 0;border-bottom:1px solid #eef2f7"><span><b>${esc(e.title)}</b><br><small class="muted">${esc(client(e.clientId)?.name||'Cliente')} · ${esc(e.type)}</small></span><span>${fmtDate(e.startAt)}</span></div>`).join('')||'<div class="empty">No hay actividades próximas.</div>'}</div></div>`;
}
function clients(){return `<div class="row" style="margin-bottom:14px"><div class="muted">Clientes y sus planes</div><button class="btn" data-newclient>+ Nuevo cliente</button></div><div class="card"><table class="table"><thead><tr><th>Cliente</th><th>Rubro</th><th>Plan</th><th>Progreso</th><th>Estado</th><th></th></tr></thead><tbody>${db.clients.map(c=>{const rs=allReels().filter(r=>String(r.clientId)===String(c.id)),pub=rs.filter(r=>r.status==='Publicado').length;return `<tr><td><b><span class="client-dot" style="background:${esc(c.color)}"></span>${esc(c.name)}</b><br><small class="muted">${esc(c.contact||'Sin contacto')}</small></td><td>${esc(c.rubric)}</td><td>${c.plan} reels</td><td><div class="progress"><div style="width:${Math.min(100,Math.round(pub/Math.max(1,c.plan)*100))}%"></div></div><small>${pub}/${c.plan} publicados</small></td><td><span class="badge">${esc(c.status)}</span></td><td><div class="actions"><button class="btn small" data-openclient="${c.id}">Abrir</button><button class="btn small secondary" data-editclient="${c.id}">Editar</button></div></td></tr>`}).join('')}</tbody></table></div>`;}
function clientDetail(){const c=client(state.clientId);if(!c){state.view='clients';return clients();}const rs=allReels().filter(r=>String(r.clientId)===String(c.id)),payments=db.payments.filter(p=>String(p.clientId)===String(c.id)),paid=payments.reduce((a,p)=>a+Number(p.amount),0),due=Math.max(0,Number(c.planPrice)-paid);return `<div class="row" style="margin-bottom:16px"><button class="btn secondary small" data-view="clients">← Volver</button><div class="actions"><button class="btn secondary small" data-editclient="${c.id}">Editar cliente</button><button class="btn secondary small" data-accessclient="${c.id}">🔐 Acceso cliente</button><button class="btn secondary small" data-newpayment="${c.id}">+ Registrar pago</button><button class="btn small" data-newreelclient="${c.id}">+ Nuevo Reel</button></div></div><div class="grid stats">${stat('Reels del plan',c.plan)}${stat('Publicados',rs.filter(r=>r.status==='Publicado').length)}${stat('Plan',money(c.planPrice))}${stat('Saldo',money(due))}</div><div class="grid two" style="margin-top:16px"><div class="card"><h3>${esc(c.name)}</h3><p class="muted">${esc(c.category)} · ${esc(c.rubric)}</p><p><b>Contacto:</b> ${esc(c.contact||'—')}</p><p><b>WhatsApp:</b> ${esc(c.phone||'—')}</p><p><b>Instagram:</b> ${esc(c.instagram||'—')}</p><p><b>Plan:</b> ${c.plan} reels · ${money(c.planPrice)}</p><p><b>Pagado:</b> ${money(paid)} · <b>Falta:</b> ${money(due)}</p><p><b>Notas:</b> ${esc(c.notes||'—')}</p></div><div class="card"><div class="row"><h3>💰 Pagos</h3><span class="badge">${money(paid)}</span></div>${payments.map(p=>`<div class="row" style="padding:9px 0;border-bottom:1px solid #eef2f7"><span><b>${money(p.amount)}</b><br><small class="muted">${fmtDate(p.paidAt)} · ${esc(p.method||'Sin medio')}</small></span><small>${esc(p.note||'')}</small></div>`).join('')||'<div class="empty">Todavía no hay pagos.</div>'}</div></div><div class="card" style="margin-top:16px"><div class="row"><h3>🎬 Estado de contenidos</h3><span class="badge">${rs.length} cargados</span></div>${rs.map(r=>`<div class="row" style="padding:9px 0;border-bottom:1px solid #eef2f7"><span><b>${esc(r.title)}</b><br><small class="muted">${esc(r.format)} · ${r.published?fmtDate(r.published):'sin publicación'}</small></span><select data-status="${r.id}">${REEL_STATUSES.map(x=>`<option ${x===r.status?'selected':''}>${x}</option>`).join('')}</select></div>`).join('')||'<div class="empty">No hay reels.</div>'}</div>`;}
function content(){const list=allReels().filter(r=>state.contentFilter==='Todos'||r.status===state.contentFilter);return `<div class="row" style="margin-bottom:14px"><div class="actions">${['Todos',...REEL_STATUSES].map(f=>`<button class="btn small ${state.contentFilter===f?'':'secondary'}" data-filter="${esc(f)}">${esc(f)}</button>`).join('')}</div>${db.user.role==='admin'?'<button class="btn" data-newreel>+ Nuevo Reel</button>':''}</div><div class="card"><table class="table"><thead><tr><th>Cliente</th><th>Reel</th><th>Estado</th><th>Publicado</th><th>Stats</th><th>Aprobación</th></tr></thead><tbody>${list.map(r=>`<tr><td>${esc(client(r.clientId)?.name||'Cliente')}</td><td><b>${esc(r.title)}</b><br><small class="muted">${esc(r.format)}</small></td><td>${db.user.role==='admin'?`<select data-status="${r.id}">${REEL_STATUSES.map(x=>`<option ${x===r.status?'selected':''}>${x}</option>`).join('')}</select>`:`<span class="badge">${esc(r.status)}</span>`}</td><td>${fmtDate(r.published)}</td><td>${r.status==='Publicado'&&db.user.role==='admin'?`<button class="btn small" data-capture="${r.id}">📸 Actualizar</button>`:'—'}</td><td>${db.user.role==='client'?`<select data-approval="${r.id}">${APPROVALS.map(x=>`<option ${x===r.approvalStatus?'selected':''}>${x}</option>`).join('')}</select>`:`<span class="badge">${esc(r.approvalStatus)}</span>`}</td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">No hay contenidos.</div></td></tr>'}</tbody></table></div>`;}
function calendar(){const now=new Date(),y=now.getFullYear(),m=now.getMonth(),days=new Date(y,m+1,0).getDate(),first=new Date(y,m,1).getDay(),offset=(first+6)%7,cells=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'].map(d=>`<div class="calendar-weekday">${d}</div>`);for(let i=0;i<offset;i++)cells.push('<div class="calendar-day calendar-empty"></div>');for(let d=1;d<=days;d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,ev=(db.events||[]).filter(e=>String(e.startAt).startsWith(key)),rs=allReels().filter(r=>r.published&&String(r.published).startsWith(key)),items=[...ev.map(e=>({kind:'event',e})),...rs.map(r=>({kind:'reel',r}))];cells.push(`<div class="calendar-day"><div class="calendar-day-head"><button class="calendar-day-number" type="button" data-day="${key}">${d}</button><button class="calendar-day-open" type="button" data-day="${key}">Ver día</button></div>${items.slice(0,4).map(it=>it.kind==='event'?`<div class="calendar-item calendar-event" style="border-left-color:${esc(client(it.e.clientId)?.color||'#0ea5e9')}"><small><b>${esc(client(it.e.clientId)?.name||'Cliente')}</b> · ${esc(it.e.type)}</small><br>${esc(it.e.title)}<br><small>🕐 ${new Date(it.e.startAt).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}</small></div>`:`<div class="calendar-item" style="border-left-color:${esc(client(it.r.clientId)?.color||'#0ea5e9')}"><small><b>${esc(client(it.r.clientId)?.name||'Cliente')}</b></small><br>🎬 ${esc(it.r.title)}<br><small>🕐 ${new Date(it.r.published).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')}${items.length>4?`<button class="calendar-more" type="button" data-day="${key}">+ ${items.length-4} más</button>`:''}</div>`);}return `<div class="card"><div class="row"><div><h3>📅 Calendario · ${now.toLocaleDateString('es-AR',{month:'long',year:'numeric'})}</h3><div class="muted">Organizá visitas, grabaciones y publicaciones por día y horario.</div></div><div class="actions"><button class="btn secondary" data-new-event>+ Actividad</button><button class="btn" data-newreel>+ Nuevo Reel</button></div></div><div class="calendar-legend"><span>🌅 Mañana · 08:00–12:00</span><span>🌇 Tarde · 15:00–21:00</span><span>💡 Tocá “Ver día” para administrar.</span></div><div class="calendar calendar-v16">${cells.join('')}</div></div>`;}
function dayAgenda(dateKey){const [y,m,d]=dateKey.split('-').map(Number),label=new Date(y,m-1,d).toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}),events=(db.events||[]).filter(e=>String(e.startAt).startsWith(dateKey)).sort((a,b)=>String(a.startAt).localeCompare(String(b.startAt))),morning=events.filter(e=>{const h=new Date(e.startAt).getHours();return h>=8&&h<15}),afternoon=events.filter(e=>{const h=new Date(e.startAt).getHours();return h>=15&&h<=23}),outside=events.filter(e=>!morning.includes(e)&&!afternoon.includes(e));const slot=(lab,range,list,hr)=>`<section class="agenda-slot"><div class="agenda-slot-head"><div><h3>${lab}</h3><span class="muted">${range}</span></div><button class="btn small" data-new-event-slot="${dateKey}T${String(hr).padStart(2,'0')}:00">+ Agregar</button></div>${list.length?list.map(e=>`<div class="agenda-event" style="border-left-color:${esc(client(e.clientId)?.color||'#0ea5e9')}"><div class="agenda-event-main"><div><b>${esc(client(e.clientId)?.name||'Cliente')}</b><span class="agenda-type">${esc(e.type)}</span></div><h4>${esc(e.title)}</h4><div class="muted">🕐 ${new Date(e.startAt).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}${e.note?` · ${esc(e.note)}`:''}</div></div><div class="agenda-actions"><button class="calendar-action edit" data-editevent="${e.id}">✏️ Editar</button><button class="calendar-action delete" data-deleteevent="${e.id}">🗑️ Borrar</button></div></div>`).join(''):'<div class="agenda-free">Horario libre</div>'}</section>`;return `<div class="day-agenda"><div class="row"><div><h2>📅 ${esc(label)}</h2><p class="muted">Planificá hasta dos franjas de trabajo en el día.</p></div><button class="btn" data-new-event-slot="${dateKey}T08:00">+ Nueva actividad</button></div>${slot('🌅 Mañana','08:00–12:00',morning,8)}${slot('🌇 Tarde','15:00–21:00',afternoon,15)}${outside.length?slot('🕐 Otros horarios','Fuera de las franjas habituales',outside,12):''}</div>`;}
function finances(){const payments=db.payments||[],contracted=db.clients.reduce((a,c)=>a+Number(c.planPrice||0),0),paid=payments.reduce((a,p)=>a+Number(p.amount),0),pending=Math.max(0,contracted-paid);return `<div class="grid stats">${stat('Contratado',money(contracted))}${stat('Cobrado',money(paid))}${stat('Pendiente',money(pending))}${stat('Clientes',db.clients.length)}</div><div class="card" style="margin-top:16px"><div class="row"><h3>💰 Estado de cuentas</h3><button class="btn" data-newpayment>+ Registrar pago</button></div><table class="table"><thead><tr><th>Cliente</th><th>Plan</th><th>Pagado</th><th>Saldo</th><th>Estado</th></tr></thead><tbody>${db.clients.map(c=>{const p=payments.filter(x=>String(x.clientId)===String(c.id)).reduce((a,x)=>a+Number(x.amount),0),due=Math.max(0,Number(c.planPrice)-p),st=due===0?'Pagado':p>0?'Parcial':'Pendiente';return `<tr><td><b>${esc(c.name)}</b></td><td>${money(c.planPrice)}</td><td>${money(p)}</td><td>${money(due)}</td><td><span class="badge">${st}</span></td></tr>`}).join('')}</tbody></table></div>`;}
function messages(){const msgs=db.messages||[], grouped=db.user.role==='admin'?db.clients.map(c=>({c,msgs:msgs.filter(m=>String(m.clientId)===String(c.id))})).filter(x=>x.msgs.length):[{c:db.clients[0],msgs}];return `<div class="row" style="margin-bottom:14px"><div class="muted">Mensajería privada por cliente. Los mensajes se guardan en Supabase.</div><div class="actions">${db.user.role==='admin'?'<button class="btn" data-newconversation>+ Nueva conversación</button>':''}</div></div><div class="messages-layout">${grouped.map(x=>{const list=x.msgs.map(m=>`<div class="message ${m.senderUserId===db.user.id?'mine':'theirs'}"><div class="message-bubble"><small>${esc(m.senderName)} · ${fmtDate(m.createdAt)}</small><div>${esc(m.body)}</div></div></div>`).join('');return `<div class="card message-card"><div class="row"><div><h3 style="margin:0">💬 ${esc(x.c?.name||'Cliente')}</h3><small class="muted">Conversación privada</small></div><span class="badge">${x.msgs.filter(m=>m.senderUserId!==db.user.id&&!m.readAt).length} sin leer</span></div><div class="message-list">${list||'<div class="empty">Todavía no hay mensajes.</div>'}</div><div class="message-compose"><textarea data-msg-input="${x.c?.id||''}" placeholder="Escribí un mensaje…"></textarea><button class="btn" data-send-message="${x.c?.id||''}">Enviar</button></div></div>`;}).join('')||'<div class="card empty">Todavía no hay conversaciones.</div>'}</div>`;}
function stats(){const rows=allReels().filter(r=>r.stats.length);return `<div class="grid two">${rows.map(r=>{const a=r.stats[0],b=r.stats[r.stats.length-1];return `<div class="card"><div class="row"><div><h3>${esc(r.title)}</h3><div class="muted">${esc(client(r.clientId)?.name||'Cliente')}</div></div>${db.user.role==='admin'?`<button class="btn small" data-capture="${r.id}">📸 Captura</button>`:''}</div><div class="grid three" style="margin-top:14px">${kpi('Views',b.views)}${kpi('Me gusta',b.likes)}${kpi('Guardados',b.saves)}</div><div class="grid two" style="margin-top:10px">${kpi('Compartidos',b.shares)}${kpi('Reposteos',b.reposts)}</div><p class="pill">Crecimiento de views: +${Math.max(0,b.views-a.views)}</p></div>`}).join('')||'<div class="card empty">Todavía no hay estadísticas cargadas.</div>'}</div>`;}
function portfolio(){return `<div class="notice">Portafolio preparado para una futura vista pública. Todos los trabajos publicados se toman desde la misma base online.</div><div class="grid three" style="margin-top:16px">${db.clients.map(c=>`<div class="card"><h3>${esc(c.name)}</h3><div class="muted">${esc(c.rubric)}</div><p>Reels publicados: ${allReels().filter(r=>String(r.clientId)===String(c.id)&&r.status==='Publicado').length}</p></div>`).join('')||'<div class="card empty">No hay clientes.</div>'}</div>`;}
function settings(){const plans=db.plans.map(p=>`<div class="card plan-card"><div class="row"><div><b>${esc(p.name)}</b><div class="muted">${p.reels} videos${p.gift_reels?` + ${p.gift_reels} de regalo`:''} · ${money(p.price)}</div></div><button class="btn small secondary" data-editplan="${p.id}">Editar</button></div><p class="muted">${esc(p.description||'')}</p></div>`).join('');return `<div class="row" style="margin-bottom:14px"><div><h2 style="margin:0">Planes y configuración</h2><div class="muted">Los planes también quedan guardados en Supabase; no dependen de la notebook.</div></div><button class="btn" data-newplan>+ Nuevo plan</button></div><div class="grid three">${plans}</div><div class="grid two" style="margin-top:16px"><div class="card"><h3>☁️ Estado de nube</h3><p class="muted">Esta versión no usa SQLite para datos de negocio.</p><div id="supabaseStatusBox" class="notice">Comprobando…</div><button class="btn" data-checksupabase>🔄 Verificar ahora</button></div><div class="card"><h3>🎨 Apariencia</h3><p class="muted">Elegí cómo querés ver la aplicación.</p><div class="actions"><button class="btn ${state.theme==='day'?'':'secondary'}" data-set-theme="day">☀️ Día</button><button class="btn ${state.theme==='night'?'':'secondary'}" data-set-theme="night">🌙 Noche</button></div></div></div><div class="grid two" style="margin-top:16px"><div class="card"><h3>Rubros cargados</h3>${CATEGORIES.map(c=>`<div style="margin-bottom:12px"><b>${esc(c.name)}</b><div class="pill">${c.rubrics.map(esc).join(' · ')}</div></div>`).join('')}</div><div class="card"><h3>🔐 Arquitectura</h3><p>Administrador: acceso total. Cliente: únicamente sus datos. La separación se aplica en Supabase con RLS, no solamente en la interfaz.</p></div></div>`;}

function clientForm(c={}){const edit=!!c.id;const cat=c.category||CATEGORIES[0].name;const rubrics=CATEGORIES.find(x=>x.name===cat)?.rubrics||[];const custom=c.rubric&&!rubrics.includes(c.rubric);return `<h2>${edit?'Editar':'Nuevo'} cliente</h2><div class="form"><label>Nombre del negocio<input id="fName" value="${esc(c.name||'')}" placeholder="Nombre del negocio"></label><label>Contacto<input id="fContact" value="${esc(c.contact||'')}"></label><label>WhatsApp<input id="fPhone" value="${esc(c.phone||'')}"></label><label>Color<input id="fColor" type="color" value="${esc(c.color||'#0ea5e9')}" style="height:44px;padding:4px"></label><label>Instagram<input id="fInstagram" value="${esc(c.instagram||'')}" placeholder="https://instagram.com/..."></label><label>Categoría<select id="fCategory">${CATEGORIES.map(x=>`<option ${x.name===cat?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label>Rubro<select id="fRubric">${rubrics.map(x=>`<option ${x===c.rubric?'selected':''}>${esc(x)}</option>`).join('')}<option value="__custom__" ${custom?'selected':''}>➕ Otro / personalizado</option></select></label><label id="customRubricWrap" style="display:${custom?'block':'none'}">Rubro personalizado<input id="fCustomRubric" value="${custom?esc(c.rubric):''}"></label><label>Plan<select id="fPlan">${db.plans.map(p=>`<option value="${p.reels}" ${Number(p.reels)===Number(c.plan||db.plans[0]?.reels||4)?'selected':''}>${esc(p.name)} · ${money(p.price)}</option>`).join('')}</select></label><label>Precio contratado<input id="fPlanPrice" type="number" min="0" value="${Number(c.planPrice||0)}"></label><label>Estado<select id="fStatus"><option ${c.status!=='Pausado'&&c.status!=='Finalizado'?'selected':''}>Activo</option><option ${c.status==='Pausado'?'selected':''}>Pausado</option><option ${c.status==='Finalizado'?'selected':''}>Finalizado</option></select></label><label>Notas<textarea id="fNotes">${esc(c.notes||'')}</textarea></label><div class="actions"><button class="btn secondary" data-close>Cancelar</button><button class="btn" data-saveclient="${c.id||''}">${edit?'Guardar cambios':'Crear cliente'}</button></div></div>`;}
function paymentForm(clientId){return `<h2>💰 Registrar pago</h2><div class="form"><label>Cliente<select id="pClient">${db.clients.map(c=>`<option value="${c.id}" ${String(c.id)===String(clientId||'')?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Monto<input id="pAmount" type="number" min="1" placeholder="40000"></label><label>Fecha<input id="pDate" type="datetime-local" value="${new Date().toISOString().slice(0,16)}"></label><label>Medio<select id="pMethod"><option>Transferencia</option><option>Efectivo</option><option>Mercado Pago</option><option>Otro</option></select></label><label>Nota<textarea id="pNote" placeholder="Seña, pago parcial, etc."></textarea></label><div class="actions"><button class="btn secondary" data-close>Cancelar</button><button class="btn" data-savepayment>Guardar pago</button></div></div>`;}
function eventForm(e={}){const edit=!!e.id;return `<h2>📅 ${edit?'Editar actividad':'Nueva actividad'}</h2><div class="form"><label>Cliente<select id="eClient">${db.clients.map(c=>`<option value="${c.id}" ${String(c.id)===String(e.clientId||'')?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Tipo<select id="eType">${EVENT_TYPES.map(x=>`<option ${x===(e.type||'Grabación')?'selected':''}>${x}</option>`).join('')}</select></label><label>Título<input id="eTitle" value="${esc(e.title||'')}" placeholder="Grabación de 2 reels"></label><label>Fecha y hora<input id="eStart" type="datetime-local" value="${e.startAt?String(e.startAt).slice(0,16):''}"></label><label>Precio extra<input id="ePrice" type="number" min="0" value="${Number(e.price||0)}"></label><label>Estado de pago<select id="ePayment">${['No corresponde','Pendiente','Pagado'].map(x=>`<option ${x===(e.paymentStatus||'No corresponde')?'selected':''}>${x}</option>`).join('')}</select></label><label>Nota<textarea id="eNote">${esc(e.note||'')}</textarea></label><div class="actions"><button class="btn secondary" data-close>Cancelar</button>${edit?`<button class="btn danger" data-deleteevent="${e.id}">Eliminar</button>`:''}<button class="btn" data-saveevent="${edit?e.id:''}">${edit?'Guardar cambios':'Guardar actividad'}</button></div></div>`;}
function reelForm(clientId=''){return `<h2>Nuevo Reel</h2><div class="form"><label>Cliente<select id="rClient">${db.clients.map(c=>`<option value="${c.id}" ${String(c.id)===String(clientId)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Título<input id="rTitle" placeholder="Ej. Producto destacado"></label><label>Formato<input id="rFormat" placeholder="Ej. Consejo"></label><label>Estado<select id="rStatus">${REEL_STATUSES.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Fecha/hora de publicación<input id="rPublished" type="datetime-local"></label><div class="actions"><button class="btn secondary" data-close>Cancelar</button><button class="btn" id="saveReel">Crear Reel</button></div></div>`;}
function captureForm(r){const next=r.stats.length===0?'Inicial':r.stats.length===1?'24 h':'72 h';return `<h2>📸 Actualizar estadísticas</h2><p><b>${esc(r.title)}</b> · ${esc(client(r.clientId)?.name||'Cliente')}</p><div class="notice">Subí una captura de Instagram/TikTok. El OCR intentará reconocer visualizaciones, me gusta, guardados, compartidos y reposteos. Revisá los números antes de guardar.</div><div class="form" style="margin-top:12px"><label>Momento<select id="sLabel"><option>${next}</option><option>7 días</option><option>15 días</option><option>30 días</option></select></label><label>📎 Captura<input id="sImage" type="file" accept="image/png,image/jpeg,image/webp"></label><div id="ocrPreview" class="notice" style="display:none"></div><div class="actions"><button class="btn secondary" data-close>Cancelar</button><button class="btn secondary" id="analyzeStats">🔎 Analizar captura</button><button class="btn" data-savestats="${r.id}">Guardar medición</button></div><div class="grid two" style="margin-top:12px"><label>Visualizaciones<input id="s_views" type="number" min="0" value="0"></label><label>Me gusta<input id="s_likes" type="number" min="0" value="0"></label><label>Guardados<input id="s_saves" type="number" min="0" value="0"></label><label>Compartidos<input id="s_shares" type="number" min="0" value="0"></label><label>Reposteos<input id="s_reposts" type="number" min="0" value="0"></label></div></div>`;}
function planForm(p={}){const edit=!!p.id;return `<h2>${edit?'Editar plan':'Nuevo plan'}</h2><div class="form"><label>Nombre<input id="plName" value="${esc(p.name||'')}" placeholder="Pack 3 + 1 de regalo"></label><label>Videos incluidos<input id="plReels" type="number" min="0" value="${Number(p.reels||3)}"></label><label>Videos de regalo<input id="plGift" type="number" min="0" value="${Number(p.gift_reels||0)}"></label><label>Precio<input id="plPrice" type="number" min="0" value="${Number(p.price||0)}"></label><label>Descripción<textarea id="plDesc">${esc(p.description||'')}</textarea></label><div class="actions"><button class="btn secondary" data-close>Cancelar</button><button class="btn" data-saveplan="${p.id||''}">${edit?'Guardar cambios':'Crear plan'}</button></div></div>`;}
function accessForm(c){return `<h2>🔐 Acceso para ${esc(c.name)}</h2><p class="muted">Este acceso crea un usuario en Supabase Auth y lo vincula a este cliente.</p><div class="form"><label>Correo del cliente<input id="aEmail" type="email" placeholder="cliente@correo.com"></label><label>Contraseña inicial<input id="aPassword" type="password" minlength="6" placeholder="Mínimo 6 caracteres"></label><div class="actions"><button class="btn secondary" data-close>Cancelar</button><button class="btn" data-saveaccess="${c.id}">Crear acceso</button></div></div>`;}
function conversationForm(){return `<h2>💬 Nueva conversación</h2><div class="form"><label>Cliente<select id="mClient">${db.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Mensaje<textarea id="mBody" placeholder="Escribí el primer mensaje…"></textarea></label><div class="actions"><button class="btn secondary" data-close>Cancelar</button><button class="btn" data-saveconversation>Iniciar conversación</button></div></div>`;}
function modalHtml(){return `<div id="modal" class="modal hidden"><div class="card modal-card"><button class="modal-x" data-close aria-label="Cerrar">×</button><div id="modalBody"></div></div></div>`;}
function openModal(html){const m=document.getElementById('modal');if(!m)return;document.getElementById('modalBody').innerHTML=html;m.classList.remove('hidden');bindModal();}
function closeModal(){document.getElementById('modal')?.classList.add('hidden');}
function renderLoading(){document.getElementById('app').innerHTML=`<div class="login"><div class="card"><div class="brand" style="color:#0f172a">SR <span>Contenidos 2.0</span></div><h2>Conectando…</h2><p class="muted">Cargando tu sesión y tus datos desde Supabase.</p></div></div>`;}
function renderLogin(error=''){document.getElementById('app').innerHTML=`<div class="login"><div class="card"><div class="brand" style="color:#0f172a">SR <span>Contenidos 2.0</span></div><h2>Iniciar sesión</h2><p class="muted">Acceso seguro para administrador y clientes.</p><div class="form"><label>Correo<input id="loginEmail" type="email" autocomplete="username" placeholder="correo@dominio.com"></label><label>Contraseña<input id="loginPass" type="password" autocomplete="current-password"></label><button class="btn" id="loginBtn">Entrar</button><div id="loginError" class="danger-notice" style="display:${error?'block':'none'}">${esc(error)}</div></div></div></div>`;document.getElementById('loginBtn').onclick=async()=>{const btn=document.getElementById('loginBtn');btn.disabled=true;try{const {error}=await sb.auth.signInWithPassword({email:document.getElementById('loginEmail').value.trim(),password:document.getElementById('loginPass').value});if(error)throw error;await loadDb();if(!db)throw new Error('No se pudo cargar el perfil. Ejecutá el SQL de SR Contenidos 2.0.');state.view='dashboard';render();}catch(e){document.getElementById('loginError').style.display='block';document.getElementById('loginError').textContent=e.message||'No se pudo iniciar sesión.';}finally{btn.disabled=false;}};}
function renderResetPassword(error=''){document.getElementById('app').innerHTML=`<div class="login"><div class="card"><div class="brand" style="color:#0f172a">SR <span>Contenidos 2.0</span></div><h2>Restablecer contraseña</h2><p class="muted">Elegí una nueva contraseña para tu cuenta.</p><div class="form"><label>Nueva contraseña<input id="resetPass" type="password" minlength="8" autocomplete="new-password" placeholder="Mínimo 8 caracteres"></label><label>Repetir contraseña<input id="resetPass2" type="password" minlength="8" autocomplete="new-password"></label><button class="btn" id="resetBtn">Guardar nueva contraseña</button><div id="resetError" class="danger-notice" style="display:${error?'block':'none'}">${esc(error)}</div></div></div></div>`;document.getElementById('resetBtn').onclick=async()=>{const btn=document.getElementById('resetBtn');const p1=document.getElementById('resetPass').value,p2=document.getElementById('resetPass2').value;btn.disabled=true;try{if(p1.length<8)throw new Error('La contraseña debe tener al menos 8 caracteres.');if(p1!==p2)throw new Error('Las contraseñas no coinciden.');const {error}=await sb.auth.updateUser({password:p1});if(error)throw error;await sb.auth.signOut();history.replaceState({},document.title,'/');renderLogin();toast('Contraseña actualizada. Ya podés iniciar sesión.');}catch(e){document.getElementById('resetError').style.display='block';document.getElementById('resetError').textContent=e.message||'No se pudo actualizar la contraseña.';}finally{btn.disabled=false;}};}
function recoveryParams(){
  const hash=new URLSearchParams(location.hash.replace(/^#/,''));
  const query=new URLSearchParams(location.search);
  return {
    type: hash.get('type') || query.get('type') || '',
    access_token: hash.get('access_token') || '',
    refresh_token: hash.get('refresh_token') || '',
    code: query.get('code') || '',
    token_hash: query.get('token_hash') || '',
    token_type: query.get('type') || ''
  };
}
function hasRecoveryUrl(){
  const p=recoveryParams();
  return p.type==='recovery' || !!p.code || !!p.token_hash || (!!p.access_token && !!p.refresh_token);
}
async function establishRecoverySession(){
  const p=recoveryParams();
  // Support all Supabase recovery link formats: PKCE code, token_hash, or implicit hash tokens.
  if(p.code){
    const {error}=await sb.auth.exchangeCodeForSession(p.code);
    if(error)throw error;
  } else if(p.token_hash && p.token_type==='recovery'){
    const {error}=await sb.auth.verifyOtp({token_hash:p.token_hash,type:'recovery'});
    if(error)throw error;
  } else if(p.access_token && p.refresh_token){
    const {error}=await sb.auth.setSession({access_token:p.access_token,refresh_token:p.refresh_token});
    if(error)throw error;
  }
  const {data:{session}}=await sb.auth.getSession();
  if(!session)throw new Error('El enlace de recuperación es inválido o venció. Solicitá un enlace nuevo.');
  return session;
}
function view(){if(state.view==='login')return renderLogin();if(!db){renderLoading();return '';}if(state.view==='dashboard')return dashboard();if(state.view==='clients')return clients();if(state.view==='clientDetail')return clientDetail();if(state.view==='content')return content();if(state.view==='calendar')return calendar();if(state.view==='calendarDay')return dayAgenda(state.dayKey);if(state.view==='finances')return finances();if(state.view==='messages')return messages();if(state.view==='stats')return stats();if(state.view==='portfolio')return portfolio();return settings();}
function render(){applyTheme();if(state.view==='login'){renderLogin();return;}if(!db){renderLoading();return;}document.getElementById('app').innerHTML=shell(view());bind();if(state.view==='settings')setTimeout(checkCloud,0);}

async function saveClient(ev){try{const id=String(ev.currentTarget.dataset.saveclient||'');const data={name:document.getElementById('fName').value.trim(),contact:document.getElementById('fContact').value.trim(),phone:document.getElementById('fPhone').value.trim(),instagram:document.getElementById('fInstagram').value.trim(),category:document.getElementById('fCategory').value,rubric:document.getElementById('fRubric').value==='__custom__'?document.getElementById('fCustomRubric').value.trim():document.getElementById('fRubric').value,plan:Number(document.getElementById('fPlan').value),status:document.getElementById('fStatus').value,notes:document.getElementById('fNotes').value.trim(),plan_price:Number(document.getElementById('fPlanPrice').value||0),color:document.getElementById('fColor').value};if(!data.name)throw new Error('Falta el nombre del negocio.');if(id){const {error}=await sb.from('sr20_clients').update(data).eq('id',id);if(error)throw error;}else{const {data:created,error}=await sb.from('sr20_clients').insert(data).select().single();if(error)throw error;const n=data.plan||4;const reels=Array.from({length:n},(_,i)=>({client_id:created.id,title:`Contenido ${i+1}`,format:'Pendiente de formato',status:'Idea',approval_status:'Pendiente'}));if(reels.length){const {error:e}=await sb.from('sr20_reels').insert(reels);if(e){await sb.from('sr20_clients').delete().eq('id',created.id);throw e;}}}await loadDb();closeModal();render();toast(id?'Cliente actualizado en la nube.':'Cliente creado y guardado en la nube.');}catch(e){fail(e);}}
async function saveReel(){try{const data={client_id:document.getElementById('rClient').value,title:document.getElementById('rTitle').value.trim()||'Nuevo Reel',format:document.getElementById('rFormat').value.trim()||'Sin formato',status:document.getElementById('rStatus').value,approval_status:'Pendiente',published:document.getElementById('rPublished').value?new Date(document.getElementById('rPublished').value).toISOString():null};const {data:r,error}=await sb.from('sr20_reels').insert(data).select().single();if(error)throw error;if(r.published){const {error:e}=await sb.from('sr20_calendar_events').insert({client_id:r.client_id,title:`Publicar reel: ${r.title}`,type:'Publicación',start_at:r.published,payment_status:'No corresponde',note:'Evento creado automáticamente desde el Reel.'});if(e)throw e;}await loadDb();closeModal();render();toast('Reel guardado en la nube.');}catch(e){fail(e);}}
async function savePayment(){try{const data={client_id:document.getElementById('pClient').value,amount:Number(document.getElementById('pAmount').value),paid_at:new Date(document.getElementById('pDate').value).toISOString(),method:document.getElementById('pMethod').value,note:document.getElementById('pNote').value.trim()};if(!data.client_id||data.amount<=0)throw new Error('Cliente y monto son obligatorios.');const {error}=await sb.from('sr20_payments').insert(data);if(error)throw error;await loadDb();closeModal();render();toast('Pago guardado en la nube.');}catch(e){fail(e);}}
async function saveEvent(ev){try{const id=String(ev.currentTarget.dataset.saveevent||''),data={client_id:document.getElementById('eClient').value,type:document.getElementById('eType').value,title:document.getElementById('eTitle').value.trim(),start_at:new Date(document.getElementById('eStart').value).toISOString(),price:Number(document.getElementById('ePrice').value||0),payment_status:document.getElementById('ePayment').value,note:document.getElementById('eNote').value.trim()};if(!data.title)throw new Error('Completá el título.');if(!data.start_at||data.start_at==='Invalid Date')throw new Error('Completá la fecha y hora.');let q;if(id)q=await sb.from('sr20_calendar_events').update(data).eq('id',id);else q=await sb.from('sr20_calendar_events').insert(data);if(q.error)throw q.error;await loadDb();closeModal();render();toast(id?'Actividad actualizada en la nube.':'Actividad guardada en la nube.');}catch(e){fail(e);}}
async function deleteEvent(ev){try{const id=String(ev.currentTarget.dataset.deleteevent||'');if(!id||!confirm('¿Eliminar esta actividad?'))return;const {error}=await sb.from('sr20_calendar_events').delete().eq('id',id);if(error)throw error;await loadDb();closeModal();render();toast('Actividad eliminada de la nube.');}catch(e){fail(e);}}
async function setReelStatus(id,status){const {data:r,error:readErr}=await sb.from('sr20_reels').select('published,client_id').eq('id',id).single();if(readErr)throw readErr;let published=r.published||null;if(status==='Publicado'&&!published)published=new Date().toISOString();const {error}=await sb.from('sr20_reels').update({status,published}).eq('id',id);if(error)throw error;if(status==='Publicado'&&!r.published){const {error:e}=await sb.from('sr20_calendar_events').insert({client_id:r.client_id,title:`Publicado reel`,type:'Publicación',start_at:published,payment_status:'No corresponde',note:'Marcado automáticamente desde Contenidos.'});if(e)console.warn(e);}}
async function setApproval(id,status){const {error}=await sb.rpc('sr20_set_reel_approval',{target_reel:id,new_status:status});if(error)throw error;}
async function saveStats(ev){try{const reel=allReels().find(r=>String(r.id)===String(ev.currentTarget.dataset.savestats));if(!reel)throw new Error('Reel no encontrado.');const label=document.getElementById('sLabel').value;const hours=label==='24 h'?24:label==='72 h'?72:label==='7 días'?168:label==='15 días'?360:label==='30 días'?720:0;const payload={reel_id:reel.id,label,hours,views:Number(document.getElementById('s_views').value||0),likes:Number(document.getElementById('s_likes').value||0),saves:Number(document.getElementById('s_saves').value||0),shares:Number(document.getElementById('s_shares').value||0),reposts:Number(document.getElementById('s_reposts').value||0),source_image_name:document.getElementById('sImage').files[0]?.name||''};const {error}=await sb.from('sr20_stats').insert(payload);if(error)throw error;await loadDb();closeModal();render();toast(`Medición ${label} guardada en la nube.`);}catch(e){fail(e);}}
async function savePlan(ev){try{const id=String(ev.currentTarget.dataset.saveplan||'');const p={name:document.getElementById('plName').value.trim(),reels:Number(document.getElementById('plReels').value||0),gift_reels:Number(document.getElementById('plGift').value||0),price:Number(document.getElementById('plPrice').value||0),description:document.getElementById('plDesc').value.trim()};if(!p.name)throw new Error('Falta el nombre del plan.');let q=id?await sb.from('sr20_plans').update(p).eq('id',id):await sb.from('sr20_plans').insert({...p,sort_order:(db.plans.length?Math.max(...db.plans.map(x=>Number(x.sort_order)||0))+1:1)});if(q.error)throw q.error;await loadDb();closeModal();render();toast('Plan guardado en la nube.');}catch(e){fail(e);}}
async function saveConversation(){try{const clientId=document.getElementById('mClient').value,body=document.getElementById('mBody').value.trim();if(!body)throw new Error('Escribí un mensaje.');const {error}=await sb.from('sr20_messages').insert({client_id:clientId,sender_user_id:db.user.id,body});if(error)throw error;await loadDb();closeModal();render();toast('Mensaje guardado en la nube.');}catch(e){fail(e);}}
async function sendMessage(clientId){try{const input=document.querySelector(`[data-msg-input="${CSS.escape(clientId)}"]`),body=input?.value.trim();if(!body)return;const {error}=await sb.from('sr20_messages').insert({client_id:clientId,sender_user_id:db.user.id,body});if(error)throw error;await loadDb();render();toast('Mensaje enviado.');}catch(e){fail(e);}}
async function createClientAccess(ev){try{const clientId=ev.currentTarget.dataset.saveaccess,email=document.getElementById('aEmail').value.trim().toLowerCase(),password=document.getElementById('aPassword').value;if(!email||password.length<6)throw new Error('Correo requerido y contraseña de al menos 6 caracteres.');const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)throw new Error('Sesión expirada. Volvé a iniciar sesión.');const c=client(clientId);const r=await fetch('/api/client-access',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({clientId,email,password,name:c?.name||'Cliente'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo crear el acceso.');closeModal();toast('Acceso de cliente creado correctamente.');}catch(e){fail(e);}}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(file);});}
function setStatValue(id,value){const el=document.getElementById(id);if(el&&Number.isFinite(value))el.value=Math.max(0,Math.round(value));}
function extractMetric(text,labels){const t=String(text||'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();for(const label of labels){const re=new RegExp(label+'[^0-9]{0,35}([0-9][0-9., ]*)','i'),m=t.match(re);if(m){let raw=m[1].replace(/[ .]/g,'').replace(/,(?=\d{3}\b)/g,'');const v=Number(raw.replace(/\.(?=\d{3}\b)/g,''));if(Number.isFinite(v))return v;}}return null;}
async function analyzeStatsImage(){const file=document.getElementById('sImage')?.files?.[0],box=document.getElementById('ocrPreview');if(!file)return toast('Primero seleccioná una captura.','error');if(!window.Tesseract)return toast('El motor OCR todavía no terminó de cargar.','error');const btn=document.getElementById('analyzeStats');btn.disabled=true;box.style.display='block';box.textContent='Analizando captura…';try{const result=await window.Tesseract.recognize(file,'spa+eng',{logger:m=>{if(m.status==='recognizing text'&&m.progress)box.textContent=`Analizando captura… ${Math.round(m.progress*100)}%`;}});const text=result.data.text||'';const vals=[extractMetric(text,['visualizaciones','views','vistas','reproducciones']),extractMetric(text,['me gusta','likes']),extractMetric(text,['guardados','saves']),extractMetric(text,['compartidos','shares']),extractMetric(text,['reposteos','reposts','republicaciones'])];setStatValue('s_views',vals[0]);setStatValue('s_likes',vals[1]);setStatValue('s_saves',vals[2]);setStatValue('s_shares',vals[3]);setStatValue('s_reposts',vals[4]);const found=vals.filter(v=>v!==null).length;box.textContent=found?`Listo. Detecté ${found} de 5 métricas. Revisá los valores antes de guardar.`:'No pude identificar las métricas automáticamente.';}catch(e){box.textContent='No se pudo analizar la captura.';toast(e.message||'OCR falló.','error');}finally{btn.disabled=false;btn.textContent='🔎 Analizar captura';}}
async function checkCloud(){const box=document.getElementById('supabaseStatusBox');if(!box)return;try{const {error}=await sb.from('sr20_plans').select('id',{count:'exact',head:true});if(error)throw error;const r=await fetch('/healthz');if(!r.ok)throw new Error('Servidor web no disponible.');box.className='notice success';box.textContent='✅ Supabase responde y la aplicación 2.0 está trabajando en modo 100% online. Los datos de negocio no se guardan en SQLite.';}catch(e){box.className='notice danger-notice';box.textContent='❌ No se pudo verificar la nube: '+(e.message||e);}}

function bindModal(){document.querySelectorAll('#modal [data-close]').forEach(b=>b.onclick=closeModal);document.querySelectorAll('#modal [data-saveclient]').forEach(b=>b.onclick=saveClient);document.querySelectorAll('#modal [data-savepayment]').forEach(b=>b.onclick=savePayment);document.querySelectorAll('#modal [data-saveevent]').forEach(b=>b.onclick=saveEvent);document.querySelectorAll('#modal [data-deleteevent]').forEach(b=>b.onclick=deleteEvent);document.querySelectorAll('#modal [data-savestats]').forEach(b=>b.onclick=saveStats);document.querySelectorAll('#modal [data-saveplan]').forEach(b=>b.onclick=savePlan);document.querySelectorAll('#modal [data-saveconversation]').forEach(b=>b.onclick=saveConversation);document.querySelectorAll('#modal [data-saveaccess]').forEach(b=>b.onclick=createClientAccess);const sr=document.getElementById('saveReel');if(sr)sr.onclick=saveReel;const analyze=document.getElementById('analyzeStats');if(analyze)analyze.onclick=analyzeStatsImage;document.getElementById('fCategory')?.addEventListener('change',e=>{const rub=document.getElementById('fRubric'),wrap=document.getElementById('customRubricWrap');const list=(CATEGORIES.find(x=>x.name===e.target.value)?.rubrics)||[];rub.innerHTML=list.map(x=>`<option>${esc(x)}</option>`).join('')+'<option value="__custom__">➕ Otro / personalizado</option>';wrap.style.display='none';});document.getElementById('fRubric')?.addEventListener('change',e=>{document.getElementById('customRubricWrap').style.display=e.target.value==='__custom__'?'block':'none';});}
function bind(){
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render();});
 document.querySelectorAll('[data-openclient]').forEach(b=>b.onclick=()=>{state.clientId=b.dataset.openclient;state.view='clientDetail';render();});
 document.querySelectorAll('[data-newclient]').forEach(b=>b.onclick=()=>openModal(clientForm()));
 document.querySelectorAll('[data-editclient]').forEach(b=>b.onclick=()=>openModal(clientForm(client(b.dataset.editclient))));
 document.querySelectorAll('[data-accessclient]').forEach(b=>b.onclick=()=>openModal(accessForm(client(b.dataset.accessclient))));
 document.querySelectorAll('[data-newpayment]').forEach(b=>b.onclick=()=>openModal(paymentForm(b.dataset.newpayment||'')));
 document.querySelectorAll('[data-newreel], [data-newreelclient]').forEach(b=>b.onclick=()=>openModal(reelForm(b.dataset.newreelclient||'')));
 document.querySelectorAll('[data-capture]').forEach(b=>b.onclick=()=>openModal(captureForm(allReels().find(r=>String(r.id)===String(b.dataset.capture)))));
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.contentFilter=b.dataset.filter;render();});
 document.querySelectorAll('[data-status]').forEach(b=>b.onchange=async()=>{try{await setReelStatus(b.dataset.status,b.value);await loadDb();render();toast('Estado actualizado en la nube.');}catch(e){fail(e);}});
 document.querySelectorAll('[data-approval]').forEach(b=>b.onchange=async()=>{try{await setApproval(b.dataset.approval,b.value);await loadDb();render();toast('Aprobación guardada en la nube.');}catch(e){fail(e);}});
 document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.dayKey=b.dataset.day;state.view='calendarDay';render();});
 document.querySelectorAll('[data-new-event]').forEach(b=>b.onclick=()=>openModal(eventForm()));
 document.querySelectorAll('[data-editevent]').forEach(b=>b.onclick=()=>openModal(eventForm(db.events.find(e=>String(e.id)===String(b.dataset.editevent)))));
 document.querySelectorAll('[data-deleteevent]').forEach(b=>b.onclick=deleteEvent);
 document.querySelectorAll('[data-new-event-slot]').forEach(b=>b.onclick=()=>openModal(eventForm({startAt:b.dataset.newEventSlot})));
 document.querySelectorAll('[data-newconversation]').forEach(b=>b.onclick=()=>openModal(conversationForm()));
 document.querySelectorAll('[data-send-message]').forEach(b=>b.onclick=()=>sendMessage(b.dataset.sendMessage));
 document.querySelectorAll('[data-set-theme]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.setTheme;localStorage.setItem('sr20_theme',state.theme);render();});
 document.querySelectorAll('[data-newplan]').forEach(b=>b.onclick=()=>openModal(planForm()));
 document.querySelectorAll('[data-editplan]').forEach(b=>b.onclick=()=>openModal(planForm(db.plans.find(p=>String(p.id)===String(b.dataset.editplan)))));
 document.querySelectorAll('[data-checksupabase]').forEach(b=>b.onclick=checkCloud);
 document.querySelectorAll('[data-logout]').forEach(b=>b.onclick=async()=>{if(!confirm('¿Cerrar sesión?'))return;await sb.auth.signOut();db=null;state.view='login';render();});
 bindModal();
}

let recoveryMode=false;
async function start(){
  renderLoading();
  try{
    if(hasRecoveryUrl()){
      recoveryMode=true;
      await establishRecoverySession();
      // Remove one-time recovery parameters from the visible URL after the session is established.
      history.replaceState({},document.title,'/reset-password');
      state.view='reset'; renderResetPassword(); return;
    }
    const {data:{session}}=await sb.auth.getSession();
    if(!session){state.view='login';render();return;}
    await loadDb();
    state.view=db?'dashboard':'login';
    if(!db) renderLogin('No se encontró tu perfil en sr20_profiles. Ejecutá el SQL de la versión 2.0 o revisá el usuario.'); else render();
  }catch(e){console.error(e);state.view='login';renderLogin(e.message||'No se pudo cargar la aplicación.');}
}
sb.auth.onAuthStateChange(async(event)=>{
  if(event==='PASSWORD_RECOVERY'){recoveryMode=true;state.view='reset';renderResetPassword();return;}
  if(recoveryMode)return;
  if(['SIGNED_IN','TOKEN_REFRESHED'].includes(event)){try{if(!db){await loadDb();state.view='dashboard';render();}}catch(e){console.error(e);}}
  if(event==='SIGNED_OUT'){db=null;state.view='login';render();}
});
window.addEventListener('load',start);
